apiVersion: apps/v1
kind: Deployment
metadata:
  name: myplugin-deployment
  labels:
    app: myplugin-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myplugin-app
  template:
    metadata:
      labels:
        app: myplugin-app
    spec:
      containers:
      - name: myplugin
        image: sammybloom/myplugin:0.1
        ports:
        - containerPort: 80